#!/usr/bin/env bash
# Turns a fresh Ubuntu/Debian VPS into NixOS running fleet.
#
# Usage, as root on the VPS:
#   curl -fsSL https://raw.githubusercontent.com/flpdorea/fleet/main/install.sh | TS_AUTHKEY=tskey-... bash
#   ... | TS_AUTHKEY=tskey-... FLEET_CONTEXTS=personal bash    one context only
#
# WARNING: this wipes the current system. The VPS reboots into NixOS and, on
# first boot, applies this repo's flake by itself (follow: journalctl -fu fleet-bootstrap).
#
# Before running, root must accept your SSH key, because NixOS disables
# password logins:   ssh-copy-id root@VPS_IP
#
# See docs/installation.md for the full walkthrough.

# Everything lives inside main(): with "curl | bash", bash only starts running
# after it has received the whole script, so a cut-off download never half-runs.
main() {
set -euo pipefail

FLEET_REPO="${FLEET_REPO:-flpdorea/fleet}"
FLEET_BRANCH="${FLEET_BRANCH:-main}"
FLEET_CONTEXTS="${FLEET_CONTEXTS:-personal work}"
FLEET_HOSTNAME="${FLEET_HOSTNAME:-fleet}"
INFECT_REV=40f62a680bb0e8f2f607d79abfaaecd99d59401c   # elitak/nixos-infect
NIX_CHANNEL="${NIX_CHANNEL:-nixos-26.05}"

log()  { printf '\n\033[1;36m==> %s\033[0m\n' "$*"; }
die()  { printf '\033[1;31merror: %s\033[0m\n' "$*" >&2; exit 1; }
has_tty() { (: </dev/tty) 2>/dev/null; }

# ---------------------------------------------------------------- checks
[ "$(id -u)" -eq 0 ] || die "run as root"
[ -e /etc/NIXOS ] && die "this machine already runs NixOS; to update it, run: fleet-rebuild"
# shellcheck disable=SC1091
. /etc/os-release
case "${ID:-}" in ubuntu|debian) ;; *) die "only Ubuntu/Debian are supported (found: ${ID:-?})" ;; esac
case "$(uname -m)" in
  x86_64)  system=x86_64-linux ;;
  aarch64) system=aarch64-linux ;;
  *)       die "unsupported architecture: $(uname -m)" ;;
esac
case "$FLEET_REPO" in */*) ;; *) die "invalid FLEET_REPO: $FLEET_REPO" ;; esac

keys=$(grep -E '^(ssh|ecdsa|sk-)' /root/.ssh/authorized_keys 2>/dev/null || true)
[ -n "$keys" ] || die "no SSH key in /root/.ssh/authorized_keys.
NixOS disables password logins and you would be locked out. From your computer:
  ssh-copy-id root@VPS_IP
then run this command again."

contexts_nix=""
for ctx in $FLEET_CONTEXTS; do
  case "$ctx" in personal|work) contexts_nix="$contexts_nix \"$ctx\"" ;; *) die "unknown context: $ctx" ;; esac
done

if [ -z "${TS_AUTHKEY:-}" ]; then
  printf '\033[1;33mwarning: no TS_AUTHKEY. After the reboot, log in as root and run "tailscale up";\n' >&2
  printf 'the Orca servers wait for Tailscale before starting.\033[0m\n' >&2
fi

cat <<EOF

This will WIPE the current system on this VPS and install NixOS with fleet:
  repo:      github:$FLEET_REPO ($FLEET_BRANCH)
  contexts: $FLEET_CONTEXTS
  hostname:  $FLEET_HOSTNAME
EOF
if [ "${FLEET_YES:-}" != 1 ]; then
  has_tty || die "no terminal to confirm on; run with FLEET_YES=1 to skip the prompt"
  printf '\nType "nixos" to continue: ' >/dev/tty
  read -r answer </dev/tty
  [ "$answer" = nixos ] || die "cancelled"
fi

# ---------------------------------------------------------------- /etc/nixos
# nixos-infect preserves /etc/nixos. We leave the machine's flake there, plus a
# first-boot module that switches the system over to that flake.
log "Preparing /etc/nixos"
# Contabo hostnames look like vmi000000.contaboserver.net, which NixOS rejects.
hostname "$FLEET_HOSTNAME"
echo "$FLEET_HOSTNAME" >/etc/hostname
install -d -m 755 /etc/nixos
install -d -m 700 /etc/nixos/secrets

if [ -n "${TS_AUTHKEY:-}" ]; then
  printf '%s' "$TS_AUTHKEY" >/etc/nixos/secrets/ts-authkey
  chmod 600 /etc/nixos/secrets/ts-authkey
  ts_line='fleet.tailscaleAuthKeyFile = "/etc/nixos/secrets/ts-authkey";'
else
  ts_line=''
fi

keys_nix=$(printf '%s\n' "$keys" | sed 's/\r$//; s/"/\\"/g; s/.*/    "&"/')

cat >/etc/nixos/flake.nix <<EOF
# Generated by fleet's install.sh. Machine-specific parts live here;
# everything else comes from github:$FLEET_REPO.
{
  inputs.fleet.url = "github:$FLEET_REPO/$FLEET_BRANCH";
  inputs.nixpkgs.follows = "fleet/nixpkgs";

  outputs = { fleet, nixpkgs, ... }: {
    nixosConfigurations.fleet = nixpkgs.lib.nixosSystem {
      modules = [
        ./configuration.nix   # generated by nixos-infect: disk, boot, network, root
        ./fleet.nix
        fleet.nixosModules.default
        { nixpkgs.hostPlatform = "$system"; }
      ];
    };
  };
}
EOF

cat >/etc/nixos/fleet.nix <<EOF
# Generated by fleet's install.sh: this machine's choices.
{
  fleet.enable = true;
  fleet.contexts = [$contexts_nix ];
  fleet.authorizedKeys = [
$keys_nix
  ];
  $ts_line
}
EOF

cat >/etc/nixos/fleet-bootstrap.nix <<'EOF'
# First boot: switch the freshly installed NixOS over to the flake in /etc/nixos.
# Once it has succeeded, it never runs again (marker in /var/lib/fleet).
{ config, pkgs, ... }:
{
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    extra-substituters = [ "https://cache.numtide.com" ];
    extra-trusted-public-keys = [ "niks3.numtide.com-1:DTx8wZduET09hRmMtKdQDxNNthLQETkc/yaX7M4qK0g=" ];
  };
  environment.systemPackages = [ pkgs.git ];

  systemd.services.fleet-bootstrap = {
    description = "fleet: apply the flake on first boot";
    wantedBy = [ "multi-user.target" ];
    wants = [ "network-online.target" ];
    after = [ "network-online.target" ];
    unitConfig.ConditionPathExists = "!/var/lib/fleet/bootstrapped";
    # The switch runs from inside this service; restarting it midway would kill the switch.
    restartIfChanged = false;
    path = [ config.system.build.nixos-rebuild config.nix.package pkgs.git pkgs.coreutils ];
    serviceConfig = {
      Type = "oneshot";
      TimeoutStartSec = "2h";
      StandardOutput = "journal+console";
    };
    script = ''
      nixos-rebuild switch --flake /etc/nixos#fleet
      mkdir -p /var/lib/fleet
      touch /var/lib/fleet/bootstrapped
      echo "fleet: ready"
    '';
  };
}
EOF

# ---------------------------------------------------------------- nixos-infect
log "Installing NixOS (the VPS reboots by itself at the end)"
cat <<EOF
After the reboot (a few minutes):
  ssh root@VPS_IP
  journalctl -fu fleet-bootstrap     follows the first build, until "fleet: ready"

Then, for each context:
  ssh personal@VPS_IP   fleet login   fleet pair
  ssh work@VPS_IP       fleet login   fleet pair

EOF
curl -fsSL "https://raw.githubusercontent.com/elitak/nixos-infect/$INFECT_REV/nixos-infect" \
  | NIXOS_IMPORT=./fleet-bootstrap.nix NIX_CHANNEL="$NIX_CHANNEL" bash
}

main "$@"
